name: Deploy Firestore Rules

on:
  push:
    branches:
      - main
    paths:
      - 'firestore.rules'
      - 'firebase.json'
      - '.github/workflows/deploy-firestore-rules.yml'

jobs:
  deploy_rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy Firestore Rules
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules --project bg-manager-cc1fa --json
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
